name: ezEngine_ClangTidyVerification_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - dev
    exclude:
    - release

jobs:
- job: ClangTidyVerification
  timeoutInMinutes: 120
  pool:
    vmImage: 'windows-2022'
  steps:
  - task: CmdLine@2
    displayName: Free Disk Space
    inputs:
      script: dir C:\
  - checkout: self
    submodules: recursive
    fetchDepth: 1
    lfs: true
  - pwsh: |
      git fetch --no-recurse-submodules --depth=100 origin $(system.pullRequest.targetBranch)
      $curCommit = $(git rev-parse HEAD)
      git fetch --no-recurse-submodules --depth=100 origin $curCommit
      ./Utilities/clang-tidy/SetupWorkspace.ps1
    displayName: 'Download LLVM & Run CMake'
  - task: CmdLine@2
    displayName: Free Disk Space
    inputs:
      script: dir C:\
  - task: PowerShell@2
    displayName: 'Run clang-tidy'
    inputs:
      pwsh: true
      targetType: filePath
      filePath: './Utilities/clang-tidy/RunClangTidy.ps1'
      arguments: '-DiffTo "origin/$(system.pullRequest.targetBranch)" -LlvmInstallDir "$pwd\llvm" -Workspace "Workspace/clang-tidy" -Vso'
  - task: PowerShell@2
    displayName: 'Fetch suggested changes'
    condition: always()
    inputs:
      pwsh: true
      targetType: 'inline'
      script: |
        # Changes done by clang tidy on MemberProperty.h are always incorrect
        git checkout "Code/Engine/Foundation/Reflection/Implementation/MemberProperty.h"
        if(@(git status -s --untracked-files=no).Length -gt 0)
        {
          Write-Host "##vso[task.logissue type=error]clang-tidy suggested changes. Clang tidy check failed! See artifact 'clang-tidy.patch' for suggested changes. Apply patch with: git apply clang-tidy.patch" -foreground red
          git diff | Out-File -Encoding utf8NoBOM -FilePath "$(Build.ArtifactStagingDirectory)\clang-tidy.patch"
        }
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Suggested Changes'
    inputs:
      ArtifactName: 'Suggested Changes'
    condition: failed()